// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t *ui_Screen1;
lv_obj_t *ui_Panel1;
lv_obj_t *ui_Label4;
lv_obj_t *ui_Panel4;
lv_obj_t *ui_socArc;
lv_obj_t *ui_socValue;
lv_obj_t *ui_ampsArc;
lv_obj_t *ui_ampsValue;
lv_obj_t *ui_Label5;
lv_obj_t *ui_Label10;
lv_obj_t *ui_Panel10;
lv_obj_t *ui_Panel5;
lv_obj_t *ui_Panel8;
lv_obj_t *ui_Panel12;
lv_obj_t *ui_Panel13;
lv_obj_t *ui_Panel14;
lv_obj_t *ui_batteryTempValue;
lv_obj_t *ui_Panel6;
lv_obj_t *ui_Label15;
lv_obj_t *ui_kwhValue;
lv_obj_t *ui_Label17;
lv_obj_t *ui_Panel7;
lv_obj_t *ui_Label18;
// CUSTOM VARIABLES

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
lv_obj_t *ui_Screen2;
lv_obj_t *ui_motorTempArc;
lv_obj_t *ui_motorTempValue;
lv_obj_t *ui_Label1;
lv_obj_t *ui_inverterTempArc;
lv_obj_t *ui_inverterTempValue;
lv_obj_t *ui_Label2;
lv_obj_t *ui_Label3;
lv_obj_t *ui_Panel2;
lv_obj_t *ui_Panel3;
lv_obj_t *ui_inverterTempArc1;
// CUSTOM VARIABLES

// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
lv_obj_t *ui_Screen3;
lv_obj_t *ui_Panel9;
lv_obj_t *ui_Panel11;
lv_obj_t *ui_Label6;
lv_obj_t *ui_Label7;
lv_obj_t *ui_Label8;
lv_obj_t *ui_gearEdittingLabel;
// CUSTOM VARIABLES

// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
lv_obj_t *ui_Screen4;
lv_obj_t *ui_Panel15;
lv_obj_t *ui_Panel16;
lv_obj_t *ui_Label9;
lv_obj_t *ui_Label11;
lv_obj_t *ui_Label12;
lv_obj_t *ui_motorEdittingLabel;
// CUSTOM VARIABLES

// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
lv_obj_t *ui_Screen5;
lv_obj_t *ui_Label13;
lv_obj_t *ui_Panel17;
lv_obj_t *ui_Panel18;
lv_obj_t *ui_Label14;
lv_obj_t *ui_Label16;
lv_obj_t *ui_regenEditing;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Screen1_screen_init();
ui_Screen2_screen_init();
ui_Screen3_screen_init();
ui_Screen4_screen_init();
ui_Screen5_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Screen1);
}
