// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_Panel4;
extern lv_obj_t *ui_socArc;
extern lv_obj_t *ui_socValue;
extern lv_obj_t *ui_ampsArc;
extern lv_obj_t *ui_ampsValue;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_Label10;
extern lv_obj_t *ui_Panel10;
extern lv_obj_t *ui_Panel5;
extern lv_obj_t *ui_Panel8;
extern lv_obj_t *ui_Panel12;
extern lv_obj_t *ui_Panel13;
extern lv_obj_t *ui_Panel14;
extern lv_obj_t *ui_batteryTempValue;
extern lv_obj_t *ui_Panel6;
extern lv_obj_t *ui_Label15;
extern lv_obj_t *ui_kwhValue;
extern lv_obj_t *ui_Label17;
extern lv_obj_t *ui_Panel7;
extern lv_obj_t *ui_Label18;
// CUSTOM VARIABLES

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t *ui_Screen2;
extern lv_obj_t *ui_motorTempArc;
extern lv_obj_t *ui_motorTempValue;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_inverterTempArc;
extern lv_obj_t *ui_inverterTempValue;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_Panel2;
extern lv_obj_t *ui_Panel3;
extern lv_obj_t *ui_inverterTempArc1;
// CUSTOM VARIABLES

// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t *ui_Screen3;
extern lv_obj_t *ui_Panel9;
extern lv_obj_t *ui_Panel11;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_Label8;
extern lv_obj_t *ui_gearEdittingLabel;
// CUSTOM VARIABLES

// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
extern lv_obj_t *ui_Screen4;
extern lv_obj_t *ui_Panel15;
extern lv_obj_t *ui_Panel16;
extern lv_obj_t *ui_Label9;
extern lv_obj_t *ui_Label11;
extern lv_obj_t *ui_Label12;
extern lv_obj_t *ui_motorEdittingLabel;
// CUSTOM VARIABLES

// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
extern lv_obj_t *ui_Screen5;
extern lv_obj_t *ui_Label13;
extern lv_obj_t *ui_Panel17;
extern lv_obj_t *ui_Panel18;
extern lv_obj_t *ui_Label14;
extern lv_obj_t *ui_Label16;
extern lv_obj_t *ui_regenEditing;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// FONTS
LV_FONT_DECLARE( ui_font_big);
LV_FONT_DECLARE( ui_font_numbers);
LV_FONT_DECLARE( ui_font_small);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
