// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen2_screen_init(void)
{
ui_Screen2 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_motorTempArc = lv_arc_create(ui_Screen2);
lv_obj_set_width( ui_motorTempArc, 150);
lv_obj_set_height( ui_motorTempArc, 134);
lv_obj_set_x( ui_motorTempArc, 1 );
lv_obj_set_y( ui_motorTempArc, 0 );
lv_obj_set_align( ui_motorTempArc, LV_ALIGN_CENTER );
lv_arc_set_value(ui_motorTempArc, 50);
lv_obj_set_style_arc_width(ui_motorTempArc, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_motorTempArc, false, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_width(ui_motorTempArc, 12, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_motorTempArc, false, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_motorTempArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_motorTempArc, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_motorTempValue = lv_label_create(ui_Screen2);
lv_obj_set_width( ui_motorTempValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_motorTempValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_motorTempValue, -5 );
lv_obj_set_y( ui_motorTempValue, -1 );
lv_obj_set_align( ui_motorTempValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_motorTempValue,"54");
lv_obj_set_style_text_font(ui_motorTempValue, &ui_font_numbers, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_Screen2);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, -7 );
lv_obj_set_y( ui_Label1, 47 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"Motor\nC");
lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_inverterTempArc = lv_arc_create(ui_Screen2);
lv_obj_set_width( ui_inverterTempArc, 67);
lv_obj_set_height( ui_inverterTempArc, 66);
lv_obj_set_x( ui_inverterTempArc, -102 );
lv_obj_set_y( ui_inverterTempArc, 16 );
lv_obj_set_align( ui_inverterTempArc, LV_ALIGN_CENTER );
lv_arc_set_value(ui_inverterTempArc, 50);
lv_arc_set_bg_angles(ui_inverterTempArc,120,300);
lv_obj_set_style_arc_width(ui_inverterTempArc, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_inverterTempArc, false, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_inverterTempArc, lv_color_hex(0xC31AC9), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_inverterTempArc, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_inverterTempArc, 8, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_inverterTempArc, false, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_inverterTempArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_inverterTempArc, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_inverterTempValue = lv_label_create(ui_Screen2);
lv_obj_set_width( ui_inverterTempValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_inverterTempValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_inverterTempValue, -100 );
lv_obj_set_y( ui_inverterTempValue, 19 );
lv_obj_set_align( ui_inverterTempValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_inverterTempValue,"100");
lv_obj_set_style_text_font(ui_inverterTempValue, &ui_font_big, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_Screen2);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, -91 );
lv_obj_set_y( ui_Label2, 43 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"Inverter\n     C");
lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label3 = lv_label_create(ui_Screen2);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label3, 97 );
lv_obj_set_y( ui_Label3, -74 );
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"Zombieverter UI");
lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x928C8C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel2 = lv_obj_create(ui_Screen2);
lv_obj_set_width( ui_Panel2, 288);
lv_obj_set_height( ui_Panel2, 1);
lv_obj_set_x( ui_Panel2, 0 );
lv_obj_set_y( ui_Panel2, -83 );
lv_obj_set_align( ui_Panel2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x3C3B3B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel3 = lv_obj_create(ui_Screen2);
lv_obj_set_width( ui_Panel3, 288);
lv_obj_set_height( ui_Panel3, 1);
lv_obj_set_x( ui_Panel3, 0 );
lv_obj_set_y( ui_Panel3, 78 );
lv_obj_set_align( ui_Panel3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x3C3B3B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_inverterTempArc1 = lv_arc_create(ui_Screen2);
lv_obj_set_width( ui_inverterTempArc1, 67);
lv_obj_set_height( ui_inverterTempArc1, 66);
lv_obj_set_x( ui_inverterTempArc1, 92 );
lv_obj_set_y( ui_inverterTempArc1, 16 );
lv_obj_set_align( ui_inverterTempArc1, LV_ALIGN_CENTER );
lv_arc_set_value(ui_inverterTempArc1, 100);
lv_arc_set_bg_angles(ui_inverterTempArc1,20,20);
lv_arc_set_mode(ui_inverterTempArc1, LV_ARC_MODE_REVERSE);
lv_arc_set_rotation(ui_inverterTempArc1,1);
lv_obj_set_style_arc_width(ui_inverterTempArc1, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_inverterTempArc1, false, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_inverterTempArc1, lv_color_hex(0xC31AC9), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_inverterTempArc1, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_inverterTempArc1, 8, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_inverterTempArc1, false, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_inverterTempArc1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_inverterTempArc1, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

}
