// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel1 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel1, 55);
lv_obj_set_height( ui_Panel1, 4);
lv_obj_set_x( ui_Panel1, -43 );
lv_obj_set_y( ui_Panel1, 111 );
lv_obj_set_align( ui_Panel1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x8F1515), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label4 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label4, 74 );
lv_obj_set_y( ui_Label4, 53 );
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"Battery\n%");
lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel4 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel4, 288);
lv_obj_set_height( ui_Panel4, 1);
lv_obj_set_x( ui_Panel4, 0 );
lv_obj_set_y( ui_Panel4, -83 );
lv_obj_set_align( ui_Panel4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x3C3B3B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_socArc = lv_arc_create(ui_Screen1);
lv_obj_set_width( ui_socArc, 150);
lv_obj_set_height( ui_socArc, 134);
lv_obj_set_x( ui_socArc, 79 );
lv_obj_set_y( ui_socArc, 12 );
lv_obj_set_align( ui_socArc, LV_ALIGN_CENTER );
lv_arc_set_value(ui_socArc, 50);
lv_obj_set_style_arc_width(ui_socArc, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_socArc, false, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_width(ui_socArc, 12, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_socArc, false, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_socArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_socArc, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_socValue = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_socValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_socValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_socValue, 72 );
lv_obj_set_y( ui_socValue, 10 );
lv_obj_set_align( ui_socValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_socValue,"54");
lv_obj_set_style_text_font(ui_socValue, &ui_font_numbers, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ampsArc = lv_arc_create(ui_Screen1);
lv_obj_set_width( ui_ampsArc, 67);
lv_obj_set_height( ui_ampsArc, 66);
lv_obj_set_x( ui_ampsArc, -22 );
lv_obj_set_y( ui_ampsArc, 29 );
lv_obj_set_align( ui_ampsArc, LV_ALIGN_CENTER );
lv_arc_set_value(ui_ampsArc, 50);
lv_arc_set_bg_angles(ui_ampsArc,120,300);
lv_obj_set_style_arc_width(ui_ampsArc, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_ampsArc, false, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_ampsArc, lv_color_hex(0xC31AC9), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_ampsArc, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_ampsArc, 8, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_ampsArc, false, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_ampsArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ampsArc, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_ampsValue = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_ampsValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ampsValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ampsValue, -23 );
lv_obj_set_y( ui_ampsValue, 31 );
lv_obj_set_align( ui_ampsValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_ampsValue,"100");
lv_obj_set_style_text_font(ui_ampsValue, &ui_font_big, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label5 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label5, 99 );
lv_obj_set_y( ui_Label5, -74 );
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"Zombieverter UI");
lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x928C8C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label10 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label10, -14 );
lv_obj_set_y( ui_Label10, 52 );
lv_obj_set_align( ui_Label10, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label10,"Amps");
lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel10 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel10, 12);
lv_obj_set_height( ui_Panel10, 3);
lv_obj_set_x( ui_Panel10, -136 );
lv_obj_set_y( ui_Panel10, 63 );
lv_obj_set_align( ui_Panel10, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel10, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel10, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel10, lv_color_hex(0xA19F9F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel10, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel5 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel5, 12);
lv_obj_set_height( ui_Panel5, 3);
lv_obj_set_x( ui_Panel5, -94 );
lv_obj_set_y( ui_Panel5, 63 );
lv_obj_set_align( ui_Panel5, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0xA19F9F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel8 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel8, 12);
lv_obj_set_height( ui_Panel8, 3);
lv_obj_set_x( ui_Panel8, -108 );
lv_obj_set_y( ui_Panel8, 63 );
lv_obj_set_align( ui_Panel8, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0xA19F9F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel12 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel12, 12);
lv_obj_set_height( ui_Panel12, 3);
lv_obj_set_x( ui_Panel12, -122 );
lv_obj_set_y( ui_Panel12, 63 );
lv_obj_set_align( ui_Panel12, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel12, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel12, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel12, lv_color_hex(0xA19F9F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel12, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel12, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel13 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel13, 12);
lv_obj_set_height( ui_Panel13, 3);
lv_obj_set_x( ui_Panel13, -94 );
lv_obj_set_y( ui_Panel13, 68 );
lv_obj_set_align( ui_Panel13, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel13, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel13, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel13, lv_color_hex(0xC11818), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel13, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel13, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel14 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel14, 12);
lv_obj_set_height( ui_Panel14, 3);
lv_obj_set_x( ui_Panel14, -136 );
lv_obj_set_y( ui_Panel14, 68 );
lv_obj_set_align( ui_Panel14, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel14, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel14, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel14, lv_color_hex(0x309ED6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel14, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel14, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_batteryTempValue = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_batteryTempValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_batteryTempValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_batteryTempValue, -121 );
lv_obj_set_y( ui_batteryTempValue, 51 );
lv_obj_set_align( ui_batteryTempValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_batteryTempValue,"24 C");
lv_obj_set_style_text_color(ui_batteryTempValue, lv_color_hex(0xB4B1B1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_batteryTempValue, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_batteryTempValue, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel6 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel6, 288);
lv_obj_set_height( ui_Panel6, 1);
lv_obj_set_x( ui_Panel6, 0 );
lv_obj_set_y( ui_Panel6, 78 );
lv_obj_set_align( ui_Panel6, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0x3C3B3B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label15 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label15, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label15, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label15, -113 );
lv_obj_set_y( ui_Label15, -40 );
lv_obj_set_align( ui_Label15, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label15,"");
lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0x92920B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label15, 200, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_kwhValue = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_kwhValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_kwhValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_kwhValue, -113 );
lv_obj_set_y( ui_kwhValue, -48 );
lv_obj_set_align( ui_kwhValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_kwhValue,"25");
lv_obj_set_style_text_color(ui_kwhValue, lv_color_hex(0xAEA02D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_kwhValue, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_kwhValue, &ui_font_numbers, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label17 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label17, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label17, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label17, -72 );
lv_obj_set_y( ui_Label17, -39 );
lv_obj_set_align( ui_Label17, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label17,"kWh");
lv_obj_set_style_text_color(ui_Label17, lv_color_hex(0xAEA02D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label17, 250, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label17, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel7 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel7, 98);
lv_obj_set_height( ui_Panel7, 2);
lv_obj_set_x( ui_Panel7, -94 );
lv_obj_set_y( ui_Panel7, -26 );
lv_obj_set_align( ui_Panel7, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0x677503), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel7, 180, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label18 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label18, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label18, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label18, -133 );
lv_obj_set_y( ui_Label18, -7 );
lv_obj_set_align( ui_Label18, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label18,"D");
lv_obj_set_style_text_color(ui_Label18, lv_color_hex(0x008FFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label18, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label18, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

}
