// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen4_screen_init(void)
{
ui_Screen4 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel15 = lv_obj_create(ui_Screen4);
lv_obj_set_width( ui_Panel15, 288);
lv_obj_set_height( ui_Panel15, 1);
lv_obj_set_x( ui_Panel15, 0 );
lv_obj_set_y( ui_Panel15, -83 );
lv_obj_set_align( ui_Panel15, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel15, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel15, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel15, lv_color_hex(0x3C3B3B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel15, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel15, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel16 = lv_obj_create(ui_Screen4);
lv_obj_set_width( ui_Panel16, 288);
lv_obj_set_height( ui_Panel16, 1);
lv_obj_set_x( ui_Panel16, 0 );
lv_obj_set_y( ui_Panel16, 78 );
lv_obj_set_align( ui_Panel16, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel16, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel16, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel16, lv_color_hex(0x3C3B3B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel16, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel16, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label9 = lv_label_create(ui_Screen4);
lv_obj_set_width( ui_Label9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label9, 97 );
lv_obj_set_y( ui_Label9, -74 );
lv_obj_set_align( ui_Label9, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label9,"Zombieverter UI");
lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0x928C8C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label11 = lv_label_create(ui_Screen4);
lv_obj_set_width( ui_Label11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label11, -89 );
lv_obj_set_y( ui_Label11, -44 );
lv_obj_set_align( ui_Label11, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label11,"Motor");
lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0xAEA02D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label12 = lv_label_create(ui_Screen4);
lv_obj_set_width( ui_Label12, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label12, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label12, -20 );
lv_obj_set_y( ui_Label12, 20 );
lv_obj_set_align( ui_Label12, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label12,"MG1+MG2");
lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_44, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_motorEdittingLabel = lv_label_create(ui_Screen4);
lv_obj_set_width( ui_motorEdittingLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_motorEdittingLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_motorEdittingLabel, -15 );
lv_obj_set_y( ui_motorEdittingLabel, -41 );
lv_obj_set_align( ui_motorEdittingLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_motorEdittingLabel,"");
lv_obj_set_style_text_font(ui_motorEdittingLabel, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

}
